In [2]:
from sklearn.datasets import load_iris

In [4]:
iris=load_iris()

In [11]:
data=iris.data

In [22]:
y=iris.target

In [14]:
from keras.utils import to_categorical

In [23]:
targrt=to_categorical(y)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
               data, targrt, test_size=0.2)

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [29]:
scaler=MinMaxScaler()

In [30]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [31]:
sX=scaler.transform(X_train)

In [32]:
sx_test=scaler.transform(X_test)

In [33]:
from keras.models import Sequential
from keras.layers import Dense

In [36]:
model= Sequential()

In [37]:
model.add(Dense(4,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [38]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 87
Trainable params: 87
Non-trainable params: 0
_________________________________________________________________


In [39]:
model.fit(sX,y_train,epochs=500,verbose=2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 0s - loss: 1.0798 - acc: 0.2917
Epoch 2/500
 - 0s - loss: 1.0768 - acc: 0.3917
Epoch 3/500
 - 0s - loss: 1.0736 - acc: 0.3500
Epoch 4/500
 - 0s - loss: 1.0703 - acc: 0.3250
Epoch 5/500
 - 0s - loss: 1.0670 - acc: 0.3250
Epoch 6/500
 - 0s - loss: 1.0637 - acc: 0.3333
Epoch 7/500
 - 0s - loss: 1.0601 - acc: 0.3250
Epoch 8/500
 - 0s - loss: 1.0565 - acc: 0.3333
Epoch 9/500
 - 0s - loss: 1.0528 - acc: 0.3333
Epoch 10/500
 - 0s - loss: 1.0492 - acc: 0.3250
Epoch 11/500
 - 0s - loss: 1.0452 - acc: 0.3167
Epoch 12/500
 - 0s - loss: 1.0414 - acc: 0.3167
Epoch 13/500
 - 0s - loss: 1.0374 - acc: 0.3167
Epoch 14/500
 - 0s - loss: 1.0334 - acc: 0.3167
Epoch 15/500
 - 0s - loss: 1.0293 - acc: 0.3167
Epoch 16/500
 - 0s - loss: 1.0247 - acc: 0.3167
Epoch 17/500
 - 0s - loss: 1.0203 - acc: 0.3167
Epoch 18/500
 - 0s - loss: 1.0157 - acc: 0.3167
Epoch 19/500
 - 0s - loss: 1.0109 - acc: 0.3167
Epoch 20/500
 - 0s - loss: 1.0060 - acc: 0.3167
E

In [41]:
pre=model.predict_classes(sx_test)

In [46]:
test_y=y_test.argmax(axis=1)

In [47]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [49]:
print(classification_report(pre,test_y))
print(accuracy_score(pre,test_y))
print(confusion_matrix(pre,test_y))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00        12

   micro avg       1.00      1.00      1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

1.0
[[10  0  0]
 [ 0  8  0]
 [ 0  0 12]]
